package com.geekbrains.db.dao;

import com.geekbrains.db.model.Categories;
import com.geekbrains.db.model.CategoriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    long countByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    int deleteByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    int insert(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    int insertSelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    List<Categories> selectByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    Categories selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    int updateByExampleSelective(@Param("record") Categories record, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    int updateByExample(@Param("record") Categories record, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    int updateByPrimaryKeySelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Thu Dec 23 19:37:49 YEKT 2021
     */
    int updateByPrimaryKey(Categories record);
}